version: '3.7'

networks:
  myag:   
    
volumes:
  ramdisk:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
  ribat_db_vol:
#   redis_vol: bunlar named volume, docker'in icinde tutuldugu icin persist volumea donusturcez

services:

  haproxy:
    container_name: haproxy
    image: haproxy:lts
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    # - "8080:80"
    volumes:
      - /home/ribat/Desktop/case2/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /home/ribat/Desktop/case2/certs/ribat.turan.pem:/usr/local/etc/haproxy/ribat.turan.pem
    networks:
      - myag

  ws1:
    container_name: ws1
    hostname: ws1
    image: nginx:stable
    restart: always
    volumes:
      #- ./index1:/usr/share/nginx/html
      #- ./index1:/var/www/html
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - myag

  ws2:
    container_name: ws2
    hostname: ws2
    image: nginx:stable
    restart: always
    volumes:
      #- ./index2:/usr/share/nginx/html
      #- ./index2:/var/www/html
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
     - myag

  phpfpm1:
    container_name: phpfpm1
    hostname: phpfpm1
    build: .
    image: php:fpm #8.1
    volumes:
      - ./php:/var/www/html
      #- ./index2:/var/www/html
    #ports:
    #  - "9000:9000"
    restart: always
    networks:
      - myag
  
  ribat_db:
    container_name: mysqldb
    hostname: ribat_db
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ribat
      MYSQL_USER: ribat
      MYSQL_PASSWORD: ribat
      MYSQL_ROOT_PASSWORD: ribat
    # tmpfs:
    #   - /var/lib/mysql
    volumes:
      #- /mnt/tmp/mysql:/var/lib/mysql #kendi olusturdugum tmpfs
      #- ramdisk:/var/lib/mysql #tmpfs
      - ribat_db_vol:/var/lib/mysql
    networks:
      - myag

  redis_db:
    container_name: rdb
    restart: always
    image: redis:7.0
    volumes:
      - ./db_vol/redis_vol:/data
    # ports:
    #   - "6379:6379"
    networks:
     - myag


  # phpfpm2:
  #   container_name: phpfpm2
  #   build: .
  #   image: php:fpm
  #   volumes:
  #     - ./php2:/var/www/html/login
  #     #- ./index2:/var/www/html
  #   #ports:
  #   #  - "9000:9000"
  #   restart: always
  #   networks:
  #     - myag



